### ISSUE TITLE
Image creation failure, MBR overwritten

### ISSUE THREAD

**Issue by gdbinit** [inversepath/usbarmory-debian-base_image#1]
Hi guys,

Did you test this Makefile? From my experience it has some problems with the image creation, because the mkfs.ext4 command will overwrite the MBR and the generated image will not work. The problem is that mkfs will not respect the offset value when using a file, starting at 0 and overwriting the partition info set in previous steps.
I could get it to work by mounting the image into loop device and doing mkfs there.
Something like this:
${TARGET_IMG}:
	fallocate -l 3500MiB  ${TARGET_IMG}
	/sbin/parted ${TARGET_IMG} --script mklabel msdos
	/sbin/parted ${TARGET_IMG} --script mkpart primary ext4 5M 100%

debian: ${TARGET_IMG}
	/sbin/losetup /dev/loop0 ${TARGET_IMG} -o 5242880 --sizelimit 3500MiB
	/sbin/mkfs.ext4 -F /dev/loop0
	/sbin/losetup -d /dev/loop0

Any ideas about this? Using Debian 8.8 to create my custom image. It works after fixing the makefile with these changes.

Thanks,
Pedro

**Comment by andrejro** [comment]
Should be fixed now. Thank you!
