### ISSUE TITLE
Makefile cannot get kernel_conf/usbarmory_4.14.config

### ISSUE THREAD

**Issue by SuperMX** [inversepath/usbarmory-debian-base_image#10]
There was tyding going on in the other repo and now the config files for 4.14 are under
https://github.com/inversepath/usbarmory/tree/master/software/kernel_conf/mark-one

so mark-one has to be added everywhere in the Makefile to ${USBARMORY_REPO}/software/kernel_conf/  

(7 appearances)

**Comment by abarisani** [comment]
This was done here:

  https://github.com/inversepath/usbarmory-debian-base_image/commit/f4a725a14963ba34544ad85c1e250a3d2b500116

and here:

https://github.com/inversepath/usbarmory-debian-base_image/commit/bc79eaf10e05d934eb65dc3cb81c21cecf69b8d3
