### ISSUE TITLE
gpg: keyserver receive failed  - Same #9

### ISSUE THREAD

**Issue by gregoryderner** [inversepath/usbarmory-debian-base_image#11]
The same thing as in the related question. But on seeing the comment of a possible error with the packages, I tried to install them. Even though it was unsuccessful and warning that it was recent, after that, the installation worked.

![image](https://user-images.githubusercontent.com/7066018/49289949-98259a00-f48c-11e8-9ca8-2835ec822fb9.png)

**Comment by andrejro** [comment]
I do not find any issue specific to the usbarmory repository here. It seems rather something
related to your distribution.
I am closing the issue now. Feel free to re-open it in case I am missing something.
