### ISSUE TITLE
e2fsprogs 1.42.12 in Jessie doesn't support metadata_csum feature

### ISSUE THREAD

**Issue by tuxlifan** [inversepath/usbarmory-debian-base_image#4]
There could be similar case with e2fsprogs on Debian (Jessie: 1.42.12-2+b1; Stretch: 1.43.4-2 and metadata_csum enabled in /etc/mke2fs.conf) as I found in https://github.com/tuxlifan/usbarmory-devuan-base_image/issues/1 unless I missed something.

**Comment by abarisani** [comment]
@andrejro which solution would you prefer from https://github.com/tuxlifan/usbarmory-devuan-base_image/issues/1  ?

**Comment by andrejro** [comment]
There are no issues in building the image on Debian 9 (e2fsprogs 1.43.4-2).
